### ISSUE TITLE
How can I change the lineHeight property?

### ISSUE THREAD

**Issue by mblabs** [MakG10/jquery-meme-generator#2]
How can I change the lineHeight property?

**Comment by MakG10** [comment]
As of now it's not possible using configuration object. But it's a good point, I will add a lineHeight param. Currently lineHeight is set to font size in line 623:

https://github.com/MakG10/jquery-memegenerator/blob/3fbafd8e12b517415f63b17c5e00cceafe6d1a76/src/js/jquery.memegenerator.js#L623

**Comment by mblabs** [comment]
It works, thanks! I've tried to edit it in the minified version but never worked! Thank You!
