### ISSUE TITLE
Text cannot be moved on actual mobile devices?

### ISSUE THREAD

**Issue by softnayr** [MakG10/jquery-meme-generator#8]
I`m trying to make the meme generator to work on mobiles devices but text resizing does not work on those devices. It's fine in responsive view on a pc browser though.

Is this something that is beyond it's capability yet or is this feature not available on mobile yet? Any thought about this? I think I need this feature badly.

**Comment by MakG10** [comment]
Hi, I'm sorry about a late response. Meme Generator is using jQuery UI for dragging and resizing. As far as I know, jQuery UI doesn't support touch events in this regard by default. You could use something like "jQuery UI Touch Punch" to get touch events to work.
https://github.com/furf/jquery-ui-touch-punch

**Comment by softnayr** [comment]
That's fine. And yeah I used jQuery UI Touch Punch for dragging instead. So
far it looks working fine. Thanks anyway.

Ryan Bañaria
